### ISSUE TITLE
Configure jira-sync for opensource FE repos

### ISSUE THREAD

**Issue by bpatelicent** [telicent-oss/jira-sync#5]
### Background

Placeholder ticket to create the link between our OSS repos and JIRA projects.

### Task

For now, we'll just do the FE ones- Issues raised in these repos need to be fed into the Frontend Team project in JIRA https://telicent.atlassian.net/jira/software/c/projects/TELFE/boards/5

- [ ] telicent-ontology
- [ ] telicent-instance
- [ ] telicent-ontology-app
- [x] rdf-libraries
- [ ] telicent-ds

### Acceptance Criteria

when a ticket is raised in any of the above OSS repos, a corresponding JIRA ticket will be raised in the FE team board

### Anything else?

- [ ] Sanity check the tooling by sync'ing ourselves first

**Comment by rvesse** [comment]
I've opened the first PR for telicent-oss/rdf-libraries#44 so hopefully that serves as a template for others to pick up the task of adding this to other repositories as needed

**Comment by rvesse** [comment]
Unassigned myself for the time being, hopefully @ACoolmanTelicent and @bpatelicent can agree how they want to prioritise and pick up the work of enabling this on the other FE repositories

**Comment by bpatelicent** [comment]
already duplicated into jira - can close here!
